### ISSUE TITLE
Find a way to artificially lengthen blocktime/confirmations on localhost

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#184]
I love dev-prod parity, aka developing in the same exact environment that will be in production.

One major area where we lack that is in confirmation time. All too often the immediate transaction confirmations for Mint, Fund, Refund, and Claim masks the fact that in reality, users will have to wait for a while here, and we should give them a better loading experience.

I think `hardhat` and `hardhat network` have config where you can increase the block time. 

Can we do this, add the time as an ENV_VAR like:

```
BLOCK_TIME=10000
```

 to JSON RPC Node like so in the `docker-compose.yml`:

```
  openq-json-rpc-node:
    image: openq/openq-json-rpc-node:latest
    container_name: ethnode
    hostname: ethnode
    ports:
      - "8545:8545"
    env_file:
      - ./OpenQ-JSON-RPC-Node/.env
```

this way here, we can very simply be more production-like in development
